In [4]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

In [5]:
municipals = []
with open('../municipals.txt', 'r') as f:
    for line in f:
        if line.strip():
            municipals.append(line.strip())

In [3]:
# Getting the ARIMA MAE results for each
sum_pred_local_df = pd.DataFrame()
for municipal in municipals:
    for i in [1,2,3,4,5,6,7,8,9,10,11,12]:
        df = pd.read_csv(f'../ARIMA/output/Municipal/CSV/{municipal}/predictions_{i}_week_ahead.csv')
        df['Week'] = i
        sum_pred_local_df = pd.concat([sum_pred_local_df, df])
#group by week then date then sum
sum_pred_local_df = sum_pred_local_df.groupby(['Week', 'Date']).sum().reset_index()
sum_pred_local_df["Date"] = pd.to_datetime(sum_pred_local_df["Date"], format="%Y-%m-%d")
sum_pred_local_df
evaluations_mae = []
evaluations_rmse = []
for n in range(1,13):
    evaluations_mae.append(mean_absolute_error(sum_pred_local_df[sum_pred_local_df["Week"] == n]["actual"], sum_pred_local_df[sum_pred_local_df["Week"] == n]["predictions"]))
    evaluations_rmse.append(np.sqrt(mean_squared_error(sum_pred_local_df[sum_pred_local_df["Week"] == n]["actual"], sum_pred_local_df[sum_pred_local_df["Week"] == n]["predictions"])))
evaluations_arima = pd.DataFrame({'Week': [1,2,3,4,5,6,7,8,9,10,11,12], 'MAE': evaluations_mae, 'RMSE': evaluations_rmse})
evaluations_arima

    Week         MAE        RMSE
0      1   37.219703   77.398443
1      2   56.978273  122.045777
2      3   75.389303  165.014502
3      4   90.958690  197.576512
4      5  103.512266  224.415390
5      6  113.985417  243.111613
6      7  120.692905  256.192566
7      8  125.829727  264.835230
8      9  130.120298  271.042210
9     10  134.211186  274.634658
10    11  137.565603  276.364871
11    12  139.049006  276.896347

In [4]:
evaluations_arima[(evaluations_arima["Week"] == 2) & (evaluations_arima["MAE"] == 0)]

Empty DataFrame
Columns: [Week, MAE, RMSE]
Index: []

In [5]:
for municipal in municipals:
    for i in [1,2,3,4,5,6,7,8,9,10,11,12]:
        df = pd.read_csv(f'output/Municipal/CSV/{municipal}/predictions_{i}_week_ahead.csv')
        df['Week'] = i
        sum_pred_local_df = pd.concat([sum_pred_local_df, df])
#group by week then date then sum
sum_pred_local_df = sum_pred_local_df.groupby(['Week', 'Date']).sum().reset_index()
sum_pred_local_df["Date"] = pd.to_datetime(sum_pred_local_df["Date"], format="%Y-%m-%d")
sum_pred_local_df
evaluations_mae = []
evaluations_rmse = []
for n in range(1,13):
    evaluations_mae.append(mean_absolute_error(sum_pred_local_df[sum_pred_local_df["Week"] == n]["actual"], sum_pred_local_df[sum_pred_local_df["Week"] == n]["predictions"]))
    evaluations_rmse.append(np.sqrt(mean_squared_error(sum_pred_local_df[sum_pred_local_df["Week"] == n]["actual"], sum_pred_local_df[sum_pred_local_df["Week"] == n]["predictions"])))
evaluations_rf_local = pd.DataFrame({'Week': [1,2,3,4,5,6,7,8,9,10,11,12], 'MAE': evaluations_mae, 'RMSE': evaluations_rmse})
evaluations_rf_local

    Week         MAE        RMSE
0      1   51.106002  107.800705
1      2   63.281565  139.502725
2      3   71.585230  168.696630
3      4   80.114494  187.182188
4      5   88.889080  206.999915
5      6   96.476787  219.325203
6      7   99.685525  229.274085
7      8  103.147995  232.850625
8      9  103.761722  231.622433
9     10  104.468706  227.677223
10    11  106.148495  225.902779
11    12  108.010881  223.293545

In [6]:
#Get RMAE of each
rel_evaluations_local_rf = pd.DataFrame()
for n in range(1,13):
    RMAE = evaluations_rf_local[evaluations_rf_local['Week'] == n]['MAE'].values[0]/evaluations_arima[evaluations_arima['Week'] == n]['MAE'].values[0]
    RRMSE = evaluations_rf_local[evaluations_rf_local['Week'] == n]['RMSE'].values[0]/evaluations_arima[evaluations_arima['Week'] == n]['RMSE'].values[0]
    rel_evaluations_local_rf = pd.concat([rel_evaluations_local_rf, pd.DataFrame({'Week': [n], 'RMAE_local': [RMAE], 'RRMSE_local': [RRMSE]})])
rel_evaluations_local_rf = rel_evaluations_local_rf.reset_index(drop=True)
rel_evaluations_local_rf

    Week  RMAE_local  RRMSE_local
0      1    1.373090     1.392802
1      2    1.110626     1.143036
2      3    0.949541     1.022314
3      4    0.880779     0.947391
4      5    0.858730     0.922396
5      6    0.846396     0.902158
6      7    0.825944     0.894929
7      8    0.819743     0.879228
8      9    0.797429     0.854562
9     10    0.778390     0.829019
10    11    0.771621     0.817408
11    12    0.776783     0.806416

In [7]:
sum_pred_prov_df = pd.DataFrame()
for municipal in municipals:
    for i in [1,2,3,4,5,6,7,8,9,10,11,12]:
        df = pd.read_csv(f'output/Municipal/CSV/{municipal}/predictions_{i}_week_ahead.csv')
        df['Week'] = i
        sum_pred_prov_df = pd.concat([sum_pred_prov_df, df])
#group by week then date then sum
sum_pred_prov_df = sum_pred_prov_df.groupby(['Week', 'Date']).sum().reset_index()
sum_pred_prov_df["Date"] = pd.to_datetime(sum_pred_local_df["Date"], format="%Y-%m-%d")
evaluations_mae = []
evaluations_rmse = []
for n in range(1,13):
    evaluations_mae.append(mean_absolute_error(sum_pred_prov_df[sum_pred_prov_df["Week"] == n]["actual"], sum_pred_prov_df[sum_pred_prov_df["Week"] == n]["predictions"]))
    evaluations_rmse.append(np.sqrt(mean_squared_error(sum_pred_prov_df[sum_pred_prov_df["Week"] == n]["actual"], sum_pred_prov_df[sum_pred_prov_df["Week"] == n]["predictions"])))
print(len(evaluations_mae))
print(len(evaluations_rmse))
evaluations_rf_provincial = pd.DataFrame({'Week': [1,2,3,4,5,6,7,8,9,10,11,12], 'MAE': evaluations_mae, 'RMSE': evaluations_rmse})
evaluations_rf_provincial

12
12

    Week        MAE        RMSE
0      1  64.992300  131.344832
1      2  69.584858  155.005965
2      3  67.781156  172.300088
3      4  69.270298  176.175664
4      5  74.265894  187.977824
5      6  78.968158  192.623552
6      7  78.678146  198.742499
7      8  80.466263  195.706739
8      9  77.403146  183.940270
9     10  74.726226  168.076293
10    11  74.731387  160.270362
11    12  76.972757  151.817086

In [8]:
rel_evaluations_provincial_rf = pd.DataFrame()
for n in range(1,13):
    RMAE = evaluations_rf_provincial[evaluations_rf_local['Week'] == n]['MAE'].values[0]/evaluations_arima[evaluations_arima['Week'] == n]['MAE'].values[0]
    RRMSE = evaluations_rf_provincial[evaluations_rf_local['Week'] == n]['RMSE'].values[0]/evaluations_arima[evaluations_arima['Week'] == n]['RMSE'].values[0]
    rel_evaluations_provincial_rf = pd.concat([rel_evaluations_provincial_rf, pd.DataFrame({'Week': [n], 'RMAE_provincial': [RMAE], 'RRMSE_provincial': [RRMSE]})])
rmae_evaluations_provincial_rf = rel_evaluations_provincial_rf.reset_index(drop=True)
rmae_evaluations_provincial_rf

    Week  RMAE_provincial  RRMSE_provincial
0      1         1.746180          1.696996
1      2         1.221252          1.270064
2      3         0.899082          1.044151
3      4         0.761558          0.891683
4      5         0.717460          0.837633
5      6         0.692792          0.792326
6      7         0.651887          0.775754
7      8         0.639485          0.738975
8      9         0.594858          0.678641
9     10         0.556781          0.612000
10    11         0.543242          0.579923
11    12         0.553566          0.548281

In [9]:
import seaborn as sns
merged_df = pd.merge(rmae_evaluations_local_rf, rmae_evaluations_provincial_rf, on='Week')
# only get week = 1,4,8,12
#merged_df = merged_df[merged_df['Week'].isin([1,4,8,12])]
merged_df

NameError: name 'rmae_evaluations_local_rf' is not defined

In [10]:
# RMAE with ARIMA

# Merge the aggregated dataframes
merged_df_agg = pd.merge(evaluations_arima_agg, rmae_evaluations_rf_local_agg, on='Week', suffixes=('_arima', '_local_rf'))
merged_df_agg = pd.merge(merged_df_agg, rmae_evaluations_rf_provincial_agg, on='Week', suffixes=('', '_provincial_rf'))

NameError: name 'evaluations_arima_agg' is not defined

In [40]:
merged_df_agg

    Week       MAE  RMAE_local  RMAE_provincial
0      1  0.754502    2.531356         2.731562
1      2  0.709218    3.151161         3.147742
2      3  0.812157    2.793274         2.658204
3      4  0.930892    2.754054         2.829468
4      5  1.065640    2.522403         2.874126
5      6  1.164031    2.488698         2.662712
6      7  1.257446    2.378222         2.787051
7      8  1.330272    2.302316         2.493152
8      9  1.382080    2.100040         2.314395
9     10  1.426877    2.038731         2.344591
10    11  1.461122    1.954403         2.389877
11    12  1.494469    1.849916         2.144733

In [12]:
rmae_evaluations_local_rf[rmae_evaluations_local_rf['Week']==2]["RMAE_local"].max()

inf

In [24]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your merged DataFrame is called df
# Melt the DataFrame to long format
df_melted = merged_df.melt(
    id_vars=["Municipal", "Week"],
    value_vars=["RMAE_local", "RMAE_provincial"],
    var_name="Model",
    value_name="RMAE"
)

# Replace model names for clarity
df_melted["Model"] = df_melted["Model"].replace({
    "RMAE_local": "Local model",
    "RMAE_provincial": "National model"
})

# Ensure Municipal is a categorical variable with proper ordering
df_melted["Municipal"] = pd.Categorical(df_melted["Municipal"], categories=sorted(df_melted["Municipal"].unique()), ordered=True)

# Set up seaborn style
sns.set(style="whitegrid")

# Plot: Facet by forecast week
g = sns.FacetGrid(df_melted, col="Week", col_wrap=1, height=4, sharey=True, aspect=2.5)
g.map_dataframe(
    sns.barplot,
    x="Municipal", y="RMAE", hue="Model",
    palette={"Local model": "salmon", "National model": "teal"},
    errorbar=None
)

# Rotate x-axis labels and ensure they are displayed
for ax in g.axes.flat:
    ax.set_xticks(range(len(df_melted["Municipal"].cat.categories)))  # Set tick positions
    ax.set_xticklabels(df_melted["Municipal"].cat.categories, rotation=90, ha='center')  # Set tick labels
    ax.tick_params(axis='x', labelsize=8)  # Adjust font size if needed

# Set axis labels and legend
g.set_axis_labels("Municipality", "Relative Mean Absolute Error (RMAE)")
g.add_legend(title="")

# Final layout
plt.tight_layout()
plt.show()

NameError: name 'merged_df' is not defined

# Feature Importance

In [14]:
feature_imp_rf_local = pd.DataFrame()
for municipal in municipals:
    for i in [1,2,3,4,5,6,7,8,9,10,12]:
        df = pd.read_csv(f'output/Municipal/CSV/{municipal}/feature_importance_{i}_week_ahead.csv')
        df['Municipal'] = municipal
        df['Week'] = i
        feature_imp_rf_local = pd.concat([feature_imp_rf_local, df])
feature_imp_rf_local = feature_imp_rf_local.reset_index(drop=True)
feature_imp_rf_local

                    Feature  Importance Municipal  Week
0               Cases_lag_1    0.776845      Ajuy     1
1               Cases_lag_2    0.114151      Ajuy     1
2        Temperature_lag_10    0.013541      Ajuy     1
3       Precipitation_lag_2    0.008860      Ajuy     1
4         Temperature_lag_8    0.006508      Ajuy     1
...                     ...         ...       ...   ...
26615          Cases_lag_19    0.000992   Zarraga    12
26616          Cases_lag_15    0.000726   Zarraga    12
26617  Precipitation_lag_14    0.000638   Zarraga    12
26618    Temperature_lag_23    0.000370   Zarraga    12
26619                 Month    0.000018   Zarraga    12

[26620 rows x 4 columns]

In [10]:
ave_feature_imp_rf_local = feature_imp_rf_local.groupby(["Feature", "Week"])['Importance'].median().reset_index()
#Make Feature a categorical variable
ave_feature_imp_rf_local["Feature"] = pd.Categorical(ave_feature_imp_rf_local["Feature"], categories=sorted(ave_feature_imp_rf_local["Feature"].unique()), ordered=True)
ave_feature_imp_rf_local = ave_feature_imp_rf_local.sort_values(by=["Week", "Importance"], ascending=[True, False])
ave_feature_imp_rf_local

NameError: name 'feature_imp_rf_local' is not defined

In [11]:
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

# Get unique weeks
weeks = ave_feature_imp_rf_local["Week"].unique()

# Set up the figure with 2 columns
n_cols = 2
n_rows = -(-len(weeks) // n_cols)  # Calculate the number of rows needed
fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 4 * n_rows), sharey=True)

# Flatten axes for easy iteration
axes = axes.flatten()

# Plot each week's data
for i, week in enumerate(weeks):
    # Filter data for the current week
    week_data = ave_feature_imp_rf_local[ave_feature_imp_rf_local["Week"] == week]

    # Plot bar chart
    axes[i].bar(week_data["Feature"], week_data["Importance"], color="gray")

    # Set title and labels
    axes[i].set_title(f"Week {week}")
    axes[i].set_xlabel("Feature")
    axes[i].set_ylabel("Importance")

    # Rotate x-axis labels for better readability
    axes[i].set_xticks(range(len(week_data["Feature"])))
    axes[i].set_xticklabels(week_data["Feature"], rotation=90, ha='center', fontsize=8)

# Remove unused subplots
for j in range(len(weeks), len(axes)):
    fig.delaxes(axes[j])
plt.suptitle("Feature Importance by N Weeks Ahead", fontsize=16)
# Adjust layout
plt.tight_layout()
plt.show()

NameError: name 'ave_feature_imp_rf_local' is not defined

## Leave One Season Out

In [12]:
import pandas as pd

leave_one_season_out_local_rf = pd.read_csv("leave_one_season_out_evaluation.csv")
leave_one_season_out_local_rf.head()

FileNotFoundError: [Errno 2] No such file or directory: 'leave_one_season_out_evaluation.csv'

In [13]:
ave_leave_one_season_out_local_rf = leave_one_season_out_local_rf.groupby('N_week_ahead')["MAE"].median().reset_index()

NameError: name 'leave_one_season_out_local_rf' is not defined

In [14]:
ave_leave_one_season_out_local_rf

NameError: name 'ave_leave_one_season_out_local_rf' is not defined

In [15]:
# pooled
leave_one_season_out_provincial_rf = pd.read_csv("leave_one_season_out_pooled_evaluation.csv")
leave_one_season_out_provincial_rf.head()

FileNotFoundError: [Errno 2] No such file or directory: 'leave_one_season_out_pooled_evaluation.csv'

In [16]:
ave_leave_one_season_out_provincial_rf = leave_one_season_out_provincial_rf.groupby('N_week_ahead')["MAE"].median().reset_index()

NameError: name 'leave_one_season_out_provincial_rf' is not defined

In [17]:
ave_leave_one_season_out_provincial_rf

NameError: name 'ave_leave_one_season_out_provincial_rf' is not defined

In [6]:
evaluations_arima_agg = pd.DataFrame()
for i in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]:
    for municipal in municipals:
        df = pd.read_csv(f'../ARIMA/output/Municipal/CSV/{municipal}/evaluation_{i}_week_ahead.csv')
        df['Week'] = i
        df['Municipal'] = municipal
        df['RMSE'] = np.sqrt(df['MSE'])
        evaluations_arima_agg = pd.concat([evaluations_arima_agg, df])

evaluations_arima_agg

    n_week_ahead        MSE       MAE  Week      Municipal      RMSE
0              1   1.154491  0.751818     1           Ajuy  1.074472
0              1   0.290364  0.310934     1      Alimodian  0.538854
0              1   0.401857  0.331242     1         Anilao  0.633922
0              1   2.199150  0.962663     1      Badiangan  1.482953
0              1   1.637989  0.824464     1        Balasan  1.279839
..           ...        ...       ...   ...            ...       ...
0             12  38.361494  3.744557    12  Santa Barbara  6.193666
0             12  13.891304  2.478498    12           Sara  3.727104
0             12  33.576647  2.837269    12       Tigbauan  5.794536
0             12   1.751414  0.776443    12       Tubungan  1.323410
0             12   6.943229  1.551588    12        Zarraga  2.635001

[528 rows x 6 columns]

In [7]:
evaluations_rf_local_agg = pd.DataFrame()
for i in [1,2,3,4,5,6,7,8,9,10,11,12]:
    for municipal in municipals:
        df = pd.read_csv(f'output/Municipal/CSV/{municipal}/evaluation_{i}_week_ahead.csv')
        df['Week'] = i
        df['Municipal'] = municipal
        df['RMSE'] = np.sqrt(df['MSE'])
        evaluations_rf_local_agg = pd.concat([evaluations_rf_local_agg, df])
evaluations_rf_local_agg['RMAE'] = evaluations_rf_local_agg['MAE'] / evaluations_arima_agg['MAE']
evaluations_rf_local_agg['RRMSE'] = evaluations_rf_local_agg['RMSE'] / evaluations_arima_agg['RMSE']
evaluations_rf_local_agg

,n_week_ahead,MSE,MAE,Week,Municipal,RMSE,RMAE,RRMSE
0,1,9.397862,1.901819,1,Ajuy,3.065593,2.529625,2.853115
0,1,12.041004,1.593725,1,Alimodian,3.470015,5.125605,6.439614
0,1,13.810250,1.522417,1,Anilao,3.716214,4.596093,5.862255
0,1,10.053491,1.782815,1,Badiangan,3.170724,1.851963,2.138115
0,1,9.464193,1.502916,1,Balasan,3.076393,1.822901,2.403734
...,...,...,...,...,...,...,...,...
0,12,80.663462,4.125000,12,Santa Barbara,8.981284,1.101599,1.450076
0,12,45.067308,3.298077,12,Sara,6.713219,1.330676,1.801189
0,12,52.336538,3.413462,12,Tigbauan,7.234400,1.203080,1.248486
0,12,4.798077,1.163462,12,Tubungan,2.190451,1.498451,1.655157
0,12,11.894231,1.682692,12,Zarraga,3.448801,1.084497,1.308843

In [8]:
evaluations_rf_provincial_agg = pd.DataFrame()
for i in [1,2,3,4,5,6,7,8,9,10,11,12]:
    for municipal in municipals:
        df = pd.read_csv(f'output/Provincial/CSV/{municipal}/evaluation_{i}_week_ahead.csv')
        df['Week'] = i
        df['Municipal'] = municipal
        df['RMSE'] = np.sqrt(df['MSE'])
        evaluations_rf_provincial_agg = pd.concat([evaluations_rf_provincial_agg, df])
evaluations_rf_provincial_agg['RMAE'] = evaluations_rf_provincial_agg['MAE'] / evaluations_arima_agg['MAE']
evaluations_rf_provincial_agg['RRMSE'] = evaluations_rf_provincial_agg['RMSE'] / evaluations_arima_agg['RMSE']
evaluations_rf_provincial_agg

,n_week_ahead,MSE,MAE,Week,Municipal,RMSE,RMAE,RRMSE
0,1,10.326923,1.961538,1,Ajuy,3.213553,2.609059,2.990820
0,1,18.134615,2.326923,1,Alimodian,4.258476,7.483654,7.902831
0,1,9.567308,2.067308,1,Anilao,3.093106,6.241086,4.879315
0,1,9.250000,2.250000,1,Badiangan,3.041381,2.337268,2.050895
0,1,9.201923,1.875000,1,Balasan,3.033467,2.274205,2.370194
...,...,...,...,...,...,...,...,...
0,12,66.326923,4.250000,12,Santa Barbara,8.144134,1.134981,1.314913
0,12,23.115385,3.038462,12,Sara,4.807846,1.225929,1.289968
0,12,60.048077,4.375000,12,Tigbauan,7.749069,1.541976,1.337306
0,12,7.961538,2.519231,12,Tubungan,2.821620,3.244580,2.132083
0,12,12.673077,3.019231,12,Zarraga,3.559927,1.945897,1.351015

In [15]:
import seaborn as sns
merged_df = pd.merge(evaluations_rf_local_agg, evaluations_rf_provincial_agg, on=['Week','Municipal', 'n_week_ahead'], suffixes=('_local', '_provincial'))
# only get week = 1,4,8,12
#merged_df = merged_df[merged_df['Week'].isin([1,4,8,12])]
merged_df = merged_df[["Municipal", "Week", "n_week_ahead", "RMAE_local", "RMAE_provincial", "RRMSE_local", 'RRMSE_provincial']]
merged_df.to_csv("ann_merged_eval.csv", index = False)

In [16]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your merged DataFrame is called merged_df
# Melt the DataFrame to long format
df_melted = merged_df.melt(
    id_vars=["Municipal", "Week"],
    value_vars=["RMAE_local", "RMAE_provincial"],
    var_name="Model",
    value_name="RMAE"
)

# Replace model names for clarity
df_melted["Model"] = df_melted["Model"].replace({
    "RMAE_local": "Local model",
    "RMAE_provincial": "Pooled Provincial model"
})

# Ensure Municipal is a categorical variable with proper ordering
df_melted["Municipal"] = pd.Categorical(
    df_melted["Municipal"],
    categories=sorted(df_melted["Municipal"].unique()),
    ordered=True
)

# Set up seaborn style
sns.set(style="whitegrid")

# Get unique weeks
weeks = df_melted["Week"].unique()

# Create a plot for each week
for week in weeks:
    # Filter data for the current week
    week_data = df_melted[df_melted["Week"] == week]

    # Create figure
    plt.figure(figsize=(12, 6))

    # Create bar plot
    ax = sns.barplot(
        data=week_data,
        x="Municipal",
        y="RMAE",
        hue="Model",
        palette={"Local model": "salmon", "Pooled Provincial model": "teal"},
        errorbar=None
    )

    # Customize plot
    plt.title(f"ANN RMAE Comparison - Week {week}")
    plt.xlabel("Municipality")
    plt.ylabel("Relative Mean Absolute Error (RMAE)")
    plt.xticks(rotation=90)
    plt.legend()
    plt.tight_layout()

    # Save the plot
    filename = f"ANN week_{week}_rmae_plots.jpg".replace(" ", "_").lower()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.close()

In [20]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming your merged DataFrame is called merged_df
# Melt the DataFrame to long format
df_melted = merged_df.melt(
    id_vars=["Municipal", "Week"],
    value_vars=["RRMSE_local", "RRMSE_provincial"],
    var_name="Model",
    value_name="RRMSE"
)

# Replace model names for clarity
df_melted["Model"] = df_melted["Model"].replace({
    "RRMSE_local": "Local model",
    "RRMSE_provincial": "Pooled Provincial model"
})

# Ensure Municipal is a categorical variable with proper ordering
df_melted["Municipal"] = pd.Categorical(
    df_melted["Municipal"],
    categories=sorted(df_melted["Municipal"].unique()),
    ordered=True
)

# Set up seaborn style
sns.set(style="whitegrid")

# Get unique weeks
weeks = df_melted["Week"].unique()

# Create a plot for each week
for week in weeks:
    # Filter data for the current week
    week_data = df_melted[df_melted["Week"] == week]

    # Create figure
    plt.figure(figsize=(12, 6))

    # Create bar plot
    ax = sns.barplot(
        data=week_data,
        x="Municipal",
        y="RRMSE",
        hue="Model",
        palette={"Local model": "salmon", "Pooled Provincial model": "teal"},
        errorbar=None
    )

    # Customize plot
    plt.title(f"ANN RRMSE Comparison - Week {week}")
    plt.xlabel("Municipality")
    plt.ylabel("Relative Root Mean Squared Error (RRMSE)")
    plt.xticks(rotation=90)
    plt.legend()
    plt.tight_layout()

    # Save the plot
    filename = f"ANN week_{week}_rrmse_plots.jpg".replace(" ", "_").lower()
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.close()